### ISSUE TITLE
why the initial self.next() ?

### ISSUE THREAD

**Issue by jimmywarting** [feross/multistream#35]
I'm creating a class that extends MultiStream with a factory

```js
class F extends MultiStream {
  constructor() {
    // Factory
    super(cb => {
      this.doSomething(cb)
    })
  }

  doSomething(cb) {
    // ...
  }
}

const f = new F()
```

But this throws an error:

```
Must call super constructor in derived class before accessing 'this' or returning from derived constructor
```

I'm wondering why you try to do work when there is nothing that is consuming the stream.
Shouldn't the factory be called when it actually need to? Meaning after `p` gets piped to something or calling `p.read()`

**Comment by feross** [comment]
The error here doesn't seem to be related to calling `self.next()`. The error message says that you can't use `this` before `super`. This is a requirement of ES classes.

As for calling `self.next()` early, I'm pretty sure all this is doing is just setting up some listeners for the `readable` event on the first stream. We're not actually reading any data until `this._drained` becomes true, which only happens when someone tries to use the stream with `pipe()` or `read()`.
