### ISSUE TITLE
v3 migration guide? changelog?

### ISSUE THREAD

**Issue by catamphetamine** [feross/multistream#42]
There seems to be no changelog and no migration guide for v2 -> v3.
What are the breaking changes?

**Comment by feross** [comment]
The changelog is here: https://github.com/feross/multistream/commits/master The breaking change is that we updated to streams v3.

**Comment by oshihirii** [comment]
sorry for newbie question, new to streams, if multistream is `streams3` compatible, shouldn’t repo readme and description be updated to say `streams3` rather than `streams2`? 

 i’ve just finished reading this article, https://medium.com/the-node-js-collection/a-brief-history-of-node-streams-pt-2-bcb6b1fd7468, and now when i view this repo, my newbie mind asks ‘is this an up to date package’?   ie ‘is it compatible with current node releases’?   if it said `streams3`, I would think, ‘oh it *is* compatible with latest releases’.

**Comment by feross** [comment]
Thanks, updated the readme.

**Comment by oshihirii** [comment]
awesome, fyi, description at top of repo still says:

    A stream that emits multiple other streams one after another (streams2)

**Comment by feross** [comment]
Thanks, fixed
